#!/usr/bin/env python2
import platform
import re
import tarfile
from scriptine import run, path
from scriptine.shell import call
from subprocess import Popen

def download_command(tag):
    url = 'http://arxiv.org/e-print/' + tag
    file = tag + '.tar.gz'
    call(['curl', '-o', file, url])

def extract_command(tag):
    dir = path(tag)
    dir.ensure_dir()
    gz = tag + '.tar.gz'
    call(['gzip', '-df', gz])
    tar = tag + '.tar'
    if tarfile.is_tarfile(tar):
        call(['tar', 'xf', tar, '-C', tag])
    else:
        call(['mv', tar, tag + '/' + dir.basename() + '.tex'])

def compile_command(tag):
    dir = path(tag)
    with dir.as_working_dir():
        for f in path.cwd().files('*.tex'):
            if re.search('^\\\\documentclass', path(f).text(), re.MULTILINE):
                call(['texliveonfly', f])
                call(['pdflatex', '-shell-escape', f])
                log = f.replace('.tex', '.log')
                while 'Rerun to get cross-references' in path(log).text():
                    call(['pdflatex', '-shell-escape', f])

def view_command(tag):
    dir = path(tag)
    with dir.as_working_dir():
        for f in path.cwd().files('*.tex'):
            if 'documentclass' in path(f).text():
                pdf = f.replace('.tex', '.pdf')
                if platform.system() == 'Darwin':
                    call(['open', pdf])
                if platform.system() == 'Windows':
                    Popen(['sumatrapdf', pdf])
                if platform.system() == 'Linux':
                    Popen(['zathura', pdf])

def batch_command(tag):
    download_command(tag)
    extract_command(tag)
    compile_command(tag)
    view_command(tag)

if __name__ == '__main__':
    run()
